// src/app/user/profile/user-social/box/box.component.ts
import { Component, Input } from '@angular/core';
import { ConnectionMeta, ConnectionMetas, SocialAccount } from '../../../../../model/social-account';
import {
  faDiscord,
  faFacebookF,
  faInstagram,
  faMastodon,
  faSnapchatGhost,
  faTwitch,
  faTwitter,
  faYoutube,
} from '@fortawesome/free-brands-svg-icons';
import { faEnvelope, faPhone, faStar, faTrophy, faTv } from '@fortawesome/free-solid-svg-icons';

@Component({
  selector: 'app-box',
  templateUrl: './box.component.html',
  styleUrls: ['./box.component.scss']
})
export class BoxComponent {
  @Input() connection: SocialAccount;

  connectionMetas: ConnectionMetas&{ _DEFAULT: ConnectionMeta } = {
    DISCORD: {
      icon: faDiscord,
      header: 'platform.DISCORD',
    },
    EMAIL: {
      linkBase: fragment => `mailto:${fragment}`,
      icon: faEnvelope,
      header: 'platform.EMAIL',
    },
    FACEBOOK: {
      linkBase: fragment => `https://www.facebook.com/${fragment}`,
      icon: faFacebookF,
      header: 'platform.FACEBOOK',
    },
    INSTAGRAM: {
      linkBase: fragment => `https://www.instagram.com/${fragment}`,
      icon: faInstagram,
      header: 'platform.INSTAGRAM',
    },
    PHONE: {
      linkBase: fragment => `tel:${fragment}`,
      icon: faPhone,
      header: 'platform.PHONE',
    },
    NICO: {
      linkBase: fragment => `https://com.nicovideo.jp/community/${fragment}`,
      icon: faTv,
      header: 'platform.NICO',
    },
    MASTODON: {
      linkBase: (fragment) => {
        const [ username, domain ] = fragment.split('@');

        return `https://${domain}/@${username}`;
      },
      icon: faMastodon,
      header: 'platform.MASTODON',
    },
    SNAPCHAT: {
      linkBase: fragment => `https://www.snapchat.com/add/${fragment}`,
      icon: faSnapchatGhost,
      header: 'platform.SNAPCHAT',
    },
    SPEEDRUNCOM: {
      linkBase: fragment => `https://speedrun.com/user/${fragment}`,
      icon: faTrophy,
      header: 'platform.SPEEDRUNCOM',
    },
    TWITCH: {
      linkBase: fragment => `https://www.twitch.tv/${fragment}`,
      icon: faTwitch,
      header: 'platform.TWITCH',
    },
    TWITTER: {
      linkBase: fragment => `https://www.twitter.com/${fragment}`,
      icon: faTwitter,
      header: 'platform.TWITTER',
    },
    YOUTUBE: {
      linkBase: fragment => `https://www.youtube.com/@${fragment}`,
      usernameFormatter: username => `@${username}`,
      icon: faYoutube,
      header: 'platform.YOUTUBE',
    },

    _DEFAULT: {
      icon: faStar,
    },
  };

  get usernameFormatted(): string {
    const connectionMeta = this.connectionMetas[this.connection?.platform] ?? this.connectionMetas._DEFAULT;

    return connectionMeta?.usernameFormatter?.(this.connection.username) ?? this.connection.username;
  }

  get connectionMeta(): ConnectionMeta {
    const connectionMeta = this.connectionMetas[this.connection?.platform] ?? this.connectionMetas._DEFAULT;
    connectionMeta.link = connectionMeta.linkBase?.(this.connection.username);
    return connectionMeta;
  }

}

<a *ngIf="connectionMeta.link; else noLink" [href]="connectionMeta.link" target="_blank" class="social-link-container">
  <p>{{ (connectionMeta.header | translate) || connection.platform }}</p>
  <fa-icon [icon]="connectionMeta.icon" size="2x"></fa-icon>
  <p>{{ connection.username }}</p>
</a>

<ng-template #noLink>
  <div class="social-link-container">
    <p>{{ (connectionMeta.header | translate) || connection.platform }}</p>
    <fa-icon [icon]="connectionMeta.icon" size="2x"></fa-icon>
    <p>{{ connection.username }}</p>
  </div>
</ng-template>

// components/user/social/Box.vue
<template>
  <Component :is="connectionMeta.link ? 'a' : 'div'" :href="connectionMeta.link" target="_blank" class="social-link-container">
    <p>{{ $t(connectionMeta.header) || connection.platform }}</p>
    <FontAwesomeIcon :icon="connectionMeta.icon" class="icon fa-6x" />
    <p>{{ connection.username }}</p>
  </Component>
</template>

<script lang="ts">
import Vue from 'vue';
import { Connection, ConnectionMeta, ConnectionMetas } from '~/types/api/connection';

export default Vue.extend({
  props: {
    connection: {
      type: Object as () => Connection,
      default: undefined,
    },
  },

  computed: {
    connectionMeta(): ConnectionMeta {
      const connectionMeta = connectionMetas[this.connection?.platform] ?? connectionMetas._DEFAULT;
      connectionMeta.link = connectionMeta.linkBase?.(this.connection.username);
      return connectionMeta;
    },
  },
});

const connectionMetas: ConnectionMetas&{ _DEFAULT: ConnectionMeta } = {
  DISCORD: {
    icon: [ 'fab', 'discord' ],
    header: 'platform.DISCORD',
  },
  EMAIL: {
    linkBase: fragment => `mailto:${fragment}`,
    icon: [ 'fas', 'envelope' ],
    header: 'platform.EMAIL',
  },
  FACEBOOK: {
    linkBase: fragment => `https://www.facebook.com/${fragment}`,
    icon: [ 'fab', 'facebook-f' ],
    header: 'platform.FACEBOOK',
  },
  INSTAGRAM: {
    linkBase: fragment => `https://www.instagram.com/${fragment}`,
    icon: [ 'fab', 'instagram' ],
    header: 'platform.INSTAGRAM',
  },
  PHONE: {
    linkBase: fragment => `tel:${fragment}`,
    icon: [ 'fas', 'phone' ],
    header: 'platform.PHONE',
  },
  NICO: {
    linkBase: fragment => `https://com.nicovideo.jp/community/${fragment}`,
    icon: [ 'fas', 'tv' ],
    header: 'platform.NICO',
  },
  MASTODON: {
    linkBase: (fragment) => {
      const [ username, domain ] = fragment.split('@');

      return `https://${domain}/${username}`;
    },
    icon: [ 'fab', 'mastodon' ],
    header: 'platform.MASTODON',
  },
  SNAPCHAT: {
    linkBase: fragment => `https://www.snapchat.com/add/${fragment}`,
    icon: [ 'fab', 'snapchat-ghost' ],
    header: 'platform.SNAPCHAT',
  },
  SPEEDRUNCOM: {
    linkBase: fragment => `https://speedrun.com/user/${fragment}`,
    icon: [ 'fas', 'trophy' ],
    header: 'platform.SPEEDRUNCOM',
  },
  TWITCH: {
    linkBase: fragment => `https://www.twitch.tv/${fragment}`,
    icon: [ 'fab', 'twitch' ],
    header: 'platform.TWITCH',
  },
  TWITTER: {
    linkBase: fragment => `https://www.twitter.com/${fragment}`,
    icon: [ 'fab', 'twitter' ],
    header: 'platform.TWITTER',
  },

  _DEFAULT: {
    icon: [ 'fas', 'star' ],
  },
};
</script>

<style lang="scss" scoped>
.social-link-container {
  display: flex;
  flex-direction: column;
  align-items: center;
  gap: 4px;
  padding: var(--spacing);
}
</style>
