// src/app/user/profile/profile-history/submission/submission.component.ts
import { Component, Input, OnInit } from '@angular/core';
import { UserProfile } from '../../../../../model/user-profile';
import { HistoryGame, HistoryGameCategory, UserProfileHistory } from '../../../../../model/user-profile-history';
import { RunStatus } from '../../../../../model/category';

@Component({
  selector: 'app-user-profile-submission-history',
  templateUrl: './submission.component.html',
  styleUrls: ['./submission.component.scss']
})
export class SubmissionComponent implements OnInit {
  @Input() user: UserProfile;

  constructor() { }

  ngOnInit(): void {
  }

  get submissions(): UserProfileHistory[] {
    return this.user.history;
  }

  getSpan(element: UserProfileHistory|HistoryGame|HistoryGameCategory): string {
    return `span ${this.getCategories(element).length}`;
  }

  getCellColor(element: UserProfileHistory|HistoryGame|HistoryGameCategory) {
    const status = this.getCategories(element)
      .reduce((currentStatus, category) => Math.min(currentStatus, RunStatus[category.status]), Infinity);
    return {
      'is-info': status === RunStatus.VALIDATED,
      'is-primary': status === RunStatus.BONUS,
      'is-success': status === RunStatus.BACKUP,
      'is-warning': status === RunStatus.REJECTED,
    };
  }

  getCategories(element: UserProfileHistory|HistoryGame|HistoryGameCategory): Array<HistoryGameCategory> {
    return this.isCategory(element)
      ? [ element ]
      : (
        this.isGame(element)
          ? element.categories
          : element.games.reduce((categories, game) => [ ...categories, ...game.categories ], [ ] as Array<HistoryGameCategory>)
      );
  }
  isMarathon(element: UserProfileHistory|HistoryGame|HistoryGameCategory): element is UserProfileHistory {
    return Object.prototype.hasOwnProperty.call(element, 'games');
  }
  isGame(element: UserProfileHistory|HistoryGame|HistoryGameCategory): element is HistoryGame {
    return Object.prototype.hasOwnProperty.call(element, 'categories');
  }
  isCategory(element: UserProfileHistory|HistoryGame|HistoryGameCategory): element is HistoryGameCategory {
    return Object.prototype.hasOwnProperty.call(element, 'status');
  }

}

<app-element-table [isDivided]="true" class="submission-table">
  <app-element-table-cell [isHeader]="true" class="marathon">
    {{ 'marathon.submissions.table.marathon' | translate }}
  </app-element-table-cell>
  <app-element-table-cell [isHeader]="true" class="game">
    {{ 'marathon.submissions.table.game' | translate }}
  </app-element-table-cell>
  <app-element-table-cell [isHeader]="true" class="category">
    {{ 'marathon.submissions.table.category' | translate }}
  </app-element-table-cell>
  <app-element-table-cell [isHeader]="true" class="estimate">
    {{ 'marathon.submissions.table.estimate' | translate }}
  </app-element-table-cell>
  <app-element-table-cell [isHeader]="true" class="status">
    {{ 'marathon.submissions.table.status' | translate }}
  </app-element-table-cell>

  <ng-template ngFor let-marathon [ngForOf]="submissions">
    <app-element-table-cell *ngIf="getCategories(marathon).length" class="marathon"  [class]="getCellColor(marathon)" [rowEnd]="getSpan(marathon)">
      <a [routerLink]="'/marathon/' + marathon.marathonId">{{ marathon.marathonName }}</a>
      (<app-element-temporal-distance [dateTime]="marathon.marathonStartDate"></app-element-temporal-distance>)
    </app-element-table-cell>

    <ng-template ngFor let-game [ngForOf]="marathon.games">
      <app-element-table-cell *ngIf="getCategories(game).length" class="game" [class]="getCellColor(game)" [rowEnd]="getSpan(game)">
        {{ game.name }}
      </app-element-table-cell>

      <ng-template ngFor let-category [ngForOf]="game.categories">
        <app-element-table-cell class="category" [class]="getCellColor(category)">
          {{ category.name }}
        </app-element-table-cell>

        <app-element-table-cell class="estimate" [class]="getCellColor(category)">
          <app-element-temporal-duration [duration]="category.estimate"></app-element-temporal-duration>
        </app-element-table-cell>

        <app-element-table-cell class="status" [class]="getCellColor(category)">
          {{ 'marathon.selection.status.' + category.status | translate }}
        </app-element-table-cell>
      </ng-template>
    </ng-template>
  </ng-template>
</app-element-table>

// components/user/history/Submission.vue
<template>
  <div>
    <WidgetLoading :while="[ user ]" class="is-centered" />
    <ElementTable v-show="submissions" is-divided class="submission-table">
      <ElementTableCell is-header class="marathon">
        {{ $t('marathon.submissions.table.marathon') }}
      </ElementTableCell>
      <ElementTableCell is-header class="game">
        {{ $t('marathon.submissions.table.game') }}
      </ElementTableCell>
      <ElementTableCell is-header class="category">
        {{ $t('marathon.submissions.table.category') }}
      </ElementTableCell>
      <ElementTableCell is-header class="estimate">
        {{ $t('marathon.submissions.table.estimate') }}
      </ElementTableCell>
      <ElementTableCell is-header class="status">
        {{ $t('marathon.submissions.table.status') }}
      </ElementTableCell>

      <template v-for="(marathon, marathonIndex) in submissions">
        <ElementTableCell :key="`marathon-${marathonIndex}`" class="marathon" :class="getCellColor(marathon)" :row-end="getSpan(marathon)">
          <ElementLink :to="`/marathon/${marathon.marathonId}`">{{ marathon.marathonName }}</ElementLink>
          (<ElementTemporalDistance :datetime="marathon.marathonStartDate" />)
        </ElementTableCell>

        <template v-for="(game, gameIndex) in marathon.games">
          <ElementTableCell :key="`game-${marathonIndex}-${gameIndex}`" class="game" :class="getCellColor(game)" :row-end="getSpan(game)">
            {{ game.name }}
          </ElementTableCell>

          <template v-for="(category, categoryIndex) in game.categories">
            <ElementTableCell :key="`category-${marathonIndex}-${gameIndex}-${categoryIndex}`" class="category" :class="getCellColor(category)">
              {{ category.name }}
            </ElementTableCell>

            <ElementTableCell :key="`estimate-${marathonIndex}-${gameIndex}-${categoryIndex}`" class="estimate" :class="getCellColor(category)">
              <ElementTemporalDuration :duration="category.estimate" />
            </ElementTableCell>

            <ElementTableCell :key="`status-${marathonIndex}-${gameIndex}-${categoryIndex}`" class="status" :class="getCellColor(category)">
              {{ $t(`marathon.selection.status.${category.status}`) }}
            </ElementTableCell>
          </template>
        </template>
      </template>
    </ElementTable>
  </div>
</template>

<script lang="ts">
import Vue from 'vue';
import { mapActions } from 'vuex';
import { HistoryGameCategoryStatus } from '~/types/api/enums/history';
import { History, HistoryGame, HistoryGameCategory } from '~/types/api/history';
import { User, UserState } from '~/types/api/user';

export default Vue.extend({
  props: {
    userId: {
      type: String,
      default: '',
    },
  },

  async fetch(): Promise<void> {
    await Promise.allSettled([
      this.getUser(this.userId),
    ]);
  },

  computed: {
    user(): User|undefined {
      return (this.$store.state.api.user as UserState).users[this.userId];
    },
    submissions(): Array<History>|undefined {
      return this.user?.history;
    },
  },

  methods: {
    getSpan(element: History|HistoryGame): string {
      return `span ${this.getCategories(element).length}`;
    },
    getCellColor(element: History|HistoryGame|HistoryGameCategory): { 'is-success': boolean, 'is-info': boolean, 'is-primary': boolean, 'is-warning': boolean } {
      const status = this.getCategories(element)
        .reduce((currentStatus, category) => Math.min(currentStatus, HistoryGameCategoryStatus[category.status]), Infinity);
      return {
        'is-info': status === HistoryGameCategoryStatus.VALIDATED,
        'is-primary': status === HistoryGameCategoryStatus.BONUS,
        'is-success': status === HistoryGameCategoryStatus.BACKUP,
        'is-warning': status === HistoryGameCategoryStatus.REJECTED,
      };
    },
    getCategories(element: History|HistoryGame|HistoryGameCategory): Array<HistoryGameCategory> {
      return this.isCategory(element)
        ? [ element ]
        : (
            this.isGame(element)
              ? element.categories
              : element.games.reduce((categories, game) => [ ...categories, ...game.categories ], [ ] as Array<HistoryGameCategory>)
          );
    },
    isMarathon(element: History|HistoryGame|HistoryGameCategory): element is History {
      return Object.prototype.hasOwnProperty.call(element, 'games');
    },
    isGame(element: History|HistoryGame|HistoryGameCategory): element is HistoryGame {
      return Object.prototype.hasOwnProperty.call(element, 'categories');
    },
    isCategory(element: History|HistoryGame|HistoryGameCategory): element is HistoryGameCategory {
      return Object.prototype.hasOwnProperty.call(element, 'status');
    },
    ...mapActions({
      getUser: 'api/user/get',
    }),
  },
});
</script>

<style lang="scss" scoped>
.submission-table {
  grid-template-columns: repeat(5, auto);
}
</style>
