// src/app/homepage/marathons/marathons.component.ts
import { Component, Input } from '@angular/core';
import { HomepageMetadata } from '../../../model/homepage-metadata';
import { getRowParity } from '../../../assets/table';
import { Marathon } from '../../../model/marathon';

@Component({
  selector: 'app-homepage-marathons',
  templateUrl: './marathons.component.html',
  styleUrls: ['./marathons.component.scss'],
})
export class MarathonsComponent {

  @Input() homepageMarathons: HomepageMetadata;

  marathonsLists = [
    {
      key: 'live',
      label: 'homepage.marathons.live',
      timeTranslationKey: 'homepage.ends',
      timeTranslationValue: ['endDate'],
      headerClass: 'is-3',
    },
    {
      key: 'next',
      label: 'homepage.marathons.upcoming',
      timeTranslationKey: 'homepage.starts',
      timeTranslationValue: ['startDate'],
      headerClass: 'is-4',
    },
    {
      key: 'open',
      label: 'homepage.marathons.open',
      timeTranslationKey: 'homepage.submissions_close',
      timeTranslationValue: ['submissionsEndDate', 'startDate'],
      headerClass: 'is-4',
    },
    {
      key: 'moderated',
      label: 'homepage.marathons.moderated',
      timeTranslationKey: 'homepage.starts',
      timeTranslationValue: ['startDate'],
      headerClass: 'is-4',
    },
  ];

  getRowParity = getRowParity;

  shouldRenderList(key: keyof HomepageMetadata): boolean {
    return (this.homepageMarathons?.[key]?.length ?? 0) > 0;
  }

  getMarathonDistance(marathon: Marathon, keys: Array<keyof Marathon>): Date | undefined {
    return keys.map(key => marathon[key] as Date).find(date => date);
  }

}

<div class="homepage-marathons-container">
  <h3 class="title is-3">
      <span>
        {{ 'calendar.title' | translate }}
      </span>
    <span>
        (<a [routerLink]="'/calendar' | localize">{{ 'homepage.marathons.calendar' | translate }}</a>)
      </span>
  </h3>

  <app-element-table class="marathons-list-container">
    <ng-template ngFor let-marathonsList [ngForOf]="marathonsLists">
      <ng-template [ngIf]="shouldRenderList(marathonsList.key)">
        <h4 class="title" [class]="marathonsList.headerClass">
          {{ marathonsList.label | translate }}
        </h4>
        <div class="spacer"></div>
        <ng-template ngFor let-marathon let-index="index" [ngForOf]="homepageMarathons[marathonsList.key]">
          <app-element-table-cell class="marathon-name" [class]="getRowParity(index)">
            <a [routerLink]="'/marathon/' + marathon.id | localize">{{ marathon.name }}</a>
          </app-element-table-cell>
          <app-element-table-cell class="location" [class]="getRowParity(index)">
            <app-marathon-location [marathon]="marathon"></app-marathon-location>
          </app-element-table-cell>
          <app-element-table-cell class="language" [class]="getRowParity(index)">
            {{ 'language.' + marathon.language | translate }}
          </app-element-table-cell>
          <app-element-table-cell class="time" [class]="getRowParity(index)" *ngFor="let item of getTranslationData(marathon, marathonsList.timeTranslationValue) | keyvalue">
            <div [appTranslatedContent]="marathonsList.timeTranslationKey[item.key]">
              <app-element-temporal-distance *appTranslatedElement="'duration'" [dateTime]="item.value"></app-element-temporal-distance>
            </div>
          </app-element-table-cell>
        </ng-template>
        <div class="spacer"></div>
      </ng-template>
    </ng-template>
  </app-element-table>

  <!--TODO <div class="is-centered">
    <app-loading-indicator></app-loading-indicator>
  </div>-->
</div>

// components/homepage/Marathons.vue
<template>
  <div class="homepage-marathons-container">
    <h3 class="title is-3">
      <span>
        {{ $t('calendar.title') }}
      </span>
      <span>
        (<ElementLink to="/calendar">{{ $t('homepage.marathons.calendar') }}</ElementLink>)
      </span>
    </h3>

    <ElementTable v-if="homepageMarathons" class="marathons-list-container">
      <template v-for="marathonsList in marathonsLists">
        <template v-if="shouldRenderList(marathonsList.key)">
          <h4 :key="marathonsList.key + 'title'" class="title" :class="marathonsList.headerClass">
            {{ $t(marathonsList.label) }}
          </h4>
          <div :key="marathonsList.key + 'prespacer'" class="spacer" />
          <template v-for="(marathon, index) in homepageMarathons[marathonsList.key]">
            <ElementTableCell :key="marathonsList.key + 'name' + index" class="marathon-name" :class="getRowParity(index)">
              <ElementLink :to="`/marathon/${marathon.id}`">
                {{ marathon.name }}
              </ElementLink>
            </ElementTableCell>
            <ElementTableCell :key="marathonsList.key + 'location' + index" class="location" :class="getRowParity(index)">
              <MarathonLocation :marathon="marathon" />
            </ElementTableCell>
            <ElementTableCell :key="marathonsList.key + 'language' + index" class="language" :class="getRowParity(index)">
              {{ marathon.language.toLocaleUpperCase() }}
            </ElementTableCell>
            <ElementTableCell :key="marathonsList.key + 'time' + index" class="time" :class="getRowParity(index)">
              <i18n :path="marathonsList.timeTranslationKey">
                <template #duration>
                  <ElementTemporalDistance :datetime="getMarathonDistance(marathon, marathonsList.timeTranslationValue)" />
                </template>
              </i18n>
            </ElementTableCell>
          </template>
          <div :key="marathonsList.key + 'postspacer'" class="spacer" />
        </template>
      </template>
    </ElementTable>
    <div class="is-centered">
      <WidgetLoading :while="[ homepageMarathons ]" />
    </div>
  </div>
</template>

<script lang="ts">
import Vue from 'vue';
import { mapActions } from 'vuex';
import { FrontPageMarathons, Marathon, MarathonState } from '~/types/api/marathon';

export default Vue.extend({
  data() {
    return {
      marathonsLists: [
        {
          key: 'live',
          label: 'homepage.marathons.live',
          timeTranslationKey: 'homepage.ends',
          timeTranslationValue: [ 'endDate' ],
          headerClass: 'is-3',
        },
        {
          key: 'next',
          label: 'homepage.marathons.upcoming',
          timeTranslationKey: 'homepage.starts',
          timeTranslationValue: [ 'startDate' ],
          headerClass: 'is-4',
        },
        {
          key: 'open',
          label: 'homepage.marathons.open',
          timeTranslationKey: 'homepage.submissions_close',
          timeTranslationValue: [ 'submissionsEndDate', 'startDate' ],
          headerClass: 'is-4',
        },
      ],
    };
  },

  async fetch(): Promise<void> {
    await Promise.allSettled([
      this.getFrontPage(),
    ]);
  },

  computed: {
    homepageMarathons(): FrontPageMarathons|undefined {
      return (this.$store.state.api.marathon as MarathonState).frontPage;
    },
  },

  methods: {
    getRowParity(index: number): { 'is-even': boolean, 'is-odd': boolean } {
      return {
        'is-even': index % 2 === 0,
        'is-odd': index % 2 === 1,
      };
    },
    shouldRenderList(key: keyof FrontPageMarathons): boolean {
      return (this.homepageMarathons?.[key]?.length ?? 0) > 0;
    },
    getMarathonDistance(marathon: Marathon, keys: Array<keyof Marathon>): Date|undefined {
      return keys.map(key => marathon[key] as Date).find(date => date);
    },
    ...mapActions({
      getFrontPage: 'api/marathon/frontPage',
    }),
  },
});
</script>

<style lang="scss" scoped>
.homepage-marathons-container {
  width: 100%;
}

.marathons-list-container {
  grid-template-columns: repeat(4, auto);
  grid-template-columns: auto min-content min-content auto;

  > .title {
    // Span from start to finish
    grid-column: 1 / -1;
    padding-inline-start: 0;
    margin: 0;
  }

  > .location {
    display: flex;
    justify-content: center;
  }

  > .time {
    text-align: end;
  }

  > .spacer {
    // Span from start to finish
    grid-column: 1 / -1;
    height: calc(3 * var(--spacing) / 2);
  }
}
</style>
