// src/app/homepage/welcome/welcome.component.ts
import { Component } from '@angular/core';
import { faAngleDown, faCheck } from '@fortawesome/free-solid-svg-icons';

@Component({
  selector: 'app-homepage-welcome',
  templateUrl: './welcome.component.html',
  styleUrls: ['./welcome.component.scss']
})
export class WelcomeComponent {
  faCheck = faCheck;
  faAngleDown = faAngleDown;
  isFoldOpen = false;
  plannedFeatures = [
    { key: '1', complete: true },
    { key: '2', complete: false },
    { key: '3', complete: true },
    { key: '4', complete: false },
    { key: '5', complete: true },
    { key: '6', complete: false },
    { key: '7', complete: false },
    { key: 'volunteerManager', complete: false },
  ];

  openFold(): void {
    this.isFoldOpen = true;
  }
}

<div class="box"  [class]="{ 'is-open-fold' : isFoldOpen }">
  <h1 class="title">
    {{ 'homepage.welcomeTitle' | translate }}
  </h1>
  <p [innerHTML]="'homepage.welcomeText.par1' | translate"></p>

  @if (!userService.user) {
    <p>
      {{ 'homepage.welcomeText.par3' | translate }}
    </p>
    <div class="is-centered">
      <app-widget-signin-picker></app-widget-signin-picker>
    </div>
  }

  @if (sandbox) {
    <p [innerHTML]="'homepage.welcomeText.par4.sandbox_new.line1' | translate | markdown"></p>
    <p [innerHTML]="'homepage.welcomeText.par4.sandbox_new.line2' | translate | markdown"></p>
  } @else {
    <p [innerHTML]="'homepage.welcomeText.par4.prod_new' | translate | markdown"></p>
  }


  <br>

    <h3 class="title is-3 below-the-fold">
      {{ 'homepage.plannedFeatures.title' | translate }}
    </h3>
    <ul class="below-the-fold">
      @for (feature of plannedFeatures; track feature) {
        <li>
          <span>
            {{ 'homepage.plannedFeatures.' + feature.key | translate }}
          </span>
          @if (feature.complete) {
            <fa-icon [icon]="faCheck" size="sm"></fa-icon>
          }
        </li>
      }
    </ul>

    <div class="is-centered is-fold-trigger">
      <button class="button" (click)="openFold()">
        <span>
          {{ 'homepage.plannedFeatures.title' | translate }}
        </span>
        <fa-icon [icon]="faAngleDown"></fa-icon>
      </button>
    </div>
  </div>

// components/homepage/Welcome.vue
<template>
  <div class="box" :class="isOpenFoldClass">
    <h1 class="title">
      {{ $t('homepage.welcomeTitle') }}
    </h1>
    <p v-html="$t('homepage.welcomeText.par1')" />
    <p>
      {{ $t('homepage.welcomeText.par3') }}
    </p>
    <div class="is-centered">
      <WidgetSignInPicker />
      <WidgetV1Redirect />
    </div>
    <p v-html="$t('homepage.welcomeText.par4.prod')" />

    <br>

    <h3 class="title is-3 below-the-fold">
      {{ $t('homepage.plannedFeatures.title') }}
    </h3>
    <ul class="below-the-fold">
      <li v-for="feature in plannedFeatures" :key="feature.key">
        <span>
          {{ $t(`homepage.plannedFeatures.${feature.key}`) }}
        </span>
        <FontAwesomeIcon v-if="feature.complete" :icon="[ 'fas', 'check' ]" class="icon is-small" />
      </li>
    </ul>

    <div class="is-centered is-fold-trigger">
      <button class="button" @click="openFold">
        <span>
          {{ $t('homepage.plannedFeatures.title') }}
        </span>
        <FontAwesomeIcon :icon="[ 'fas', 'angle-down' ]" class="icon" />
      </button>
    </div>
  </div>
</template>

<script lang="ts">
import Vue from 'vue';

export default Vue.extend({
  data() {
    return {
      isFoldOpen: false,
      plannedFeatures: [
        { key: '1', complete: true },
        { key: '2', complete: false },
        { key: '3', complete: true },
        { key: '4', complete: false },
        { key: '5', complete: true },
        { key: '6', complete: false },
        { key: '7', complete: true },
        { key: 'volunteerManager', complete: false },
      ],
    };
  },

  computed: {
    isOpenFoldClass(): { 'is-open-fold': boolean } {
      return { 'is-open-fold': this.isFoldOpen };
    },
  },

  methods: {
    openFold(): void {
      this.isFoldOpen = true;
    },
  },
});
</script>

<style lang="scss" scoped>
ul {
  list-style: disc;
  padding-inline-start: 20px;
}

.is-fold-trigger {
  display: none;
}

@media (max-width: 1023px) {
  .is-fold-trigger {
    display: flex;

    .is-open-fold & {
      display: none;
    }
  }

  .below-the-fold {
    display: none;

    .is-open-fold & {
      display: inherit;
    }
  }
}
</style>
