// components/marathon/Details.vue
<template>
  <div v-if="marathon && !marathon._fetching" class="marathon-details-container">
    <div class="marathon-details-info-container">
      <div class="info-box">
        <p class="info-label">
          {{ $t('marathon.home.from') }}
        </p>
        <ElementTemporalDateTime :datetime="marathon.startDate" format="shortDate" class="info" />
      </div>
      <div class="info-box">
        <p class="info-label">
          {{ $t('marathon.home.to') }}
        </p>
        <ElementTemporalDateTime :datetime="marathon.endDate" format="shortDate" class="info" />
      </div>
      <div class="info-box">
        <p class="info-label">
          {{ $t('marathon.home.location') }}
        </p>
        <MarathonLocation :marathon="marathon" class="info" />
      </div>
      <div class="info-box">
        <p class="info-label">
          {{ $t('marathon.home.language') }}
        </p>
        <p class="info">
          {{ $t(`language.${marathon.language}`) }}
        </p>
      </div>
      <a v-if="marathon.twitch" :href="`https://twitch.tv/${marathon.twitch}`" target="_blank" class="info-box">
        <p class="info-label">
          {{ $t('platform.TWITCH') }}
        </p>
        <FontAwesomeIcon :icon="[ 'fab', 'twitch' ]" class="icon info" />
      </a>
      <a v-if="marathon.mastodon" :href="mastodonUrl" target="_blank" class="info-box">
        <p class="info-label">
          {{ $t('platform.MASTODON') }}
        </p>
        <FontAwesomeIcon :icon="[ 'fab', 'mastodon' ]" class="icon info" />
      </a>
      <a v-if="marathon.twitter" :href="`https://twitter.com/${marathon.twitter}`" target="_blank" class="info-box">
        <p class="info-label">
          {{ $t('platform.TWITTER') }}
        </p>
        <FontAwesomeIcon :icon="[ 'fab', 'twitter' ]" class="icon info" />
      </a>
      <a v-if="!marathon.discordPrivacy && marathon.discord" :href="`https://discord.gg/${marathon.discord}`" target="_blank" class="info-box">
        <p class="info-label">
          {{ $t('platform.DISCORD') }}
        </p>
        <FontAwesomeIcon :icon="[ 'fab', 'discord' ]" class="icon info" />
      </a>
      <a v-if="marathon.youtube" :href="marathon.youtube" target="_blank" class="info-box">
        <p class="info-label">
          {{ $t('platform.YOUTUBE') }}
        </p>
        <FontAwesomeIcon :icon="[ 'fab', 'youtube' ]" class="icon info" />
      </a>
    </div>

    <WidgetTwitchPlayer v-if="marathon.twitch && isLive" :channel="marathon.twitch" class="marathon-live-player" />
  </div>
</template>

<script lang="ts">
import Vue from 'vue';
import { mapActions } from 'vuex';
import { FullMarathon, MarathonState } from '~/types/api/marathon';

export default Vue.extend({
  props: {
    marathonId: {
      type: String,
      default: '',
    },
  },

  async fetch(): Promise<void> {
    await Promise.allSettled([
      this.getMarathon(this.marathonId),
    ]);
  },

  computed: {
    marathon(): FullMarathon|undefined {
      return (this.$store.state.api.marathon as MarathonState).marathons[this.marathonId];
    },
    mastodonUrl(): string {
      if (!this.marathon || !this.marathon.mastodon) {
        return 'https://speedrun.zone/@OengusIO';
      }

      const [ username, domain ] = this.marathon.mastodon.split('@');

      return `https://${domain}/@${username}`;
    },
    isLive(): boolean {
      if (!this.marathon) {
        return false;
      }

      const start = new Date(this.marathon.startDate).getTime();
      const end = new Date(this.marathon.endDate).getTime();
      const now = Date.now();
      return start <= now && now <= end;
    },
  },

  methods: {
    ...mapActions({
      getMarathon: 'api/marathon/get',
    }),
  },
});
</script>

<style lang="scss" scoped>
.marathon-details-container {
  display: grid;
}

.marathon-details-info-container {
  width: 100%;
  display: flex;
  flex-wrap: wrap;
  justify-content: space-evenly;
  border-block: 1px solid;
  gap: var(--spacing);
  padding: var(--spacing);

  > .info-box {
    display: flex;
    flex-direction: column;
    align-items: center;
    gap: 4px;

    .info {
      font-size: 1.75rem;
      line-height: 1;
    }
  }
}

.marathon-live-player {
  margin-block-start: var(--spacing);
  width: 100%;
  max-width: 2560px;
  height: 60vh;
  max-height: 1440px;
}
</style>

// src/app/marathon/home/details/details.component.ts
import { Component, Input, OnInit } from '@angular/core';
import { Marathon } from '../../../../model/marathon';
import { faDiscord, faTwitch, faTwitter, faYoutube, faMastodon } from '@fortawesome/free-brands-svg-icons';
import { faComputer } from '@fortawesome/free-solid-svg-icons';

@Component({
  selector: 'app-details',
  templateUrl: './details.component.html',
  styleUrls: ['./details.component.scss']
})
export class DetailsComponent implements OnInit {
  @Input() marathon: Marathon;


  public faTwitch = faTwitch;
  public faTwitter = faTwitter;
  public faMastodon = faMastodon;
  public faDiscord = faDiscord;
  public faYoutube = faYoutube;
  public faComputer = faComputer;

  constructor() { }

  ngOnInit(): void {
  }

  get isLive(): boolean {
    if (!this.marathon) {
      return false;
    }

    const start = new Date(this.marathon.startDate).getTime();
    const end = new Date(this.marathon.endDate).getTime();
    const now = Date.now();
    return start <= now && now <= end;
  }

  get mastodonUrl(): string {
    if (!this.marathon || !this.marathon.mastodon) {
      return 'https://speedrun.zone/@OengusIO';
    }

    const [ username, domain ] = this.marathon.mastodon.split('@');

    return `https://${domain}/@${username}`;
  }

}

<div class="marathon-details-info-container">
  <div class="info-box">
    <p class="info-label">
      {{ 'marathon.home.from' | translate }}
    </p>
    <app-element-temporal-datetime [dateTime]="marathon.startDate" format="shortDate" class="info"></app-element-temporal-datetime>
  </div>
  <div class="info-box">
    <p class="info-label">
      {{ 'marathon.home.to' | translate }}
    </p>
    <app-element-temporal-datetime [dateTime]="marathon.endDate" format="shortDate" class="info"></app-element-temporal-datetime>
  </div>
  <div class="info-box">
    <p class="info-label">
      {{ 'marathon.home.location' | translate }}
    </p>
    <app-marathon-location [marathon]="marathon" class="info"></app-marathon-location>
    @if (marathon.onsite && marathon.location) {
      <p>{{ marathon.location }}</p>
    }
  </div>
  <div class="info-box">
    <p class="info-label">
      {{ 'marathon.home.language' | translate }}
    </p>
    <p class="info">
      {{ 'language.' + marathon.language | translate }}
    </p>
  </div>
  @if (marathon.twitch) {
    <a [href]="'https://twitch.tv/' +  marathon.twitch + '?utm_source=Oengus'" target="_blank" class="info-box">
      <p class="info-label">
        {{ 'platform.TWITCH' | translate }}
      </p>
      <fa-icon [icon]="faTwitch" class="info"></fa-icon>
      <p>{{ marathon.twitch }}</p>
    </a>
  }
  @if (marathon.mastodon) {
    <a [href]="mastodonUrl" target="_blank" class="info-box">
      <p class="info-label">
        {{ 'platform.MASTODON' | translate }}
      </p>
      <fa-icon [icon]="faMastodon" class="info"></fa-icon>
      <p>{{ marathon.mastodon }}</p>
    </a>
  }
  @if (marathon.bluesky) {
    <a [href]="bskyUrl" target="_blank" class="info-box">
      <p class="info-label">
        {{ 'platform.BLUESKY' | translate }}
      </p>
      <fa-icon [icon]="faBluesky" class="info"></fa-icon>
      <p>{{ marathon.bluesky }}</p>
    </a>
  }
  @if (marathon.twitter) {
    <a [href]="'https://twitter.com/' + marathon.twitter + '?utm_source=Oengus'" target="_blank" class="info-box">
      <p class="info-label">
        {{ 'platform.TWITTER' | translate }}
      </p>
      <fa-icon [icon]="faTwitter" class="info"></fa-icon>
      <p>&#64;{{ marathon.twitter }}</p>
    </a>
  }
  @if (!marathon.discordPrivacy && marathon.discord) {
    <a [href]="'https://discord.gg/' + marathon.discord + '?utm_source=Oengus'" target="_blank" class="info-box">
      <p class="info-label">
        {{ 'platform.DISCORD' | translate }}
      </p>
      <fa-icon [icon]="faDiscord" class="info"></fa-icon>
    </a>
  }

  @if (marathon.youtube) {
    <a [href]="marathon.youtube + '?utm_source=Oengus'" target="_blank" class="info-box">
      <p class="info-label">
        {{ 'platform.YOUTUBE' | translate }}
      </p>
      <fa-icon [icon]="faYoutube" class="info"></fa-icon>
    </a>
  }
</div>

<!-- TODO: youtube player -->
@if (marathon.twitch && isLive) {
  <app-element-twitch-player
    [channel]="marathon.twitch"
  class="marathon-live-player"></app-element-twitch-player>
}
